---
title: "Research"
---

### Publications

**Elçi, E.**, Sert, D., & Balta, E. (2025). Electoral Pressure, Reputational Risks, and Coalition Politics:
How Established Parties Respond to The Rise of Anti-Immigrant Parties. *New Perspectives
on Turkey*. Online First. [10]

Aytaç, S. E., Çarkoğlu, A., & **Elçi, E.** (2025). Populist Appeals, Emotions, and Political Mobilization. *American Behavioral Scientist, 69*(5), 507-525.

**Elçi, E.** (2024). Nostalgia and Populism. In T. Becker & D. Trigg (eds.), *Routledge Handbook on Nostalgia*. London & New York: Routledge.

Kirişçioğlu, E., Üstübici, A., **Elçi, E.** (2024). Migration Aspirations in Relation to Border Closures, Employment Opportunities and Risk-Taking Attitudes: Lessons from an Online Survey Experiment. *Journal of Ethnic and Migration Studies. 50*(18), 4395-441.

**Elçi, E.** (2024). Right-Wing Populism In Turkey And 2023 Elections. *Southeast European and Black Sea Studies, 24*(2), 297–317.

**Elçi, E.** (2024). Authoritarian Populism. In N. Lindstaedt & J. Van den Bosch (eds.), *Research Handbook on Authoritarianism.* Cheltenham: Edward Elgar Publishing.

**Elçi, E.** (2024). Türkiye’de Dini Yönetime Destek: Dünya Değerler Araştırması Analizi (Support for a Religious System in Turkey: A World Values Survey Analysis), *Akdeniz İİBF Dergisi, 24*(1), 14-26.

Balta, E., **Elçi, E.**, & Sert, D. (2023). *The 2023 Elections and Migration Debate in Turkey.* Istanbul: Heinrich Böll Stiftung.

Çarkoğlu, A., & **Elçi, E.** (2023). Populist Attitudes and Challenges Towards Liberal Democracy: A Survey Analysis. *International Political Science Review, 44*(5), 729–746.

Balta, E., **Elçi, E.**, & Sert, D. (2023). *Political Party Representation of Anti-Immigration Attitudes: The Case of Turkey.* Istanbul: Heinrich Böll Stiftung.

Üstübici, A., & **Elçi, E.** (2022). Aspirations among Young Refugees in Turkey: Social Class, Integration and Onward Migration in Forced Migration Contexts. *Journal of Ethnic and Migration Studies, 48*(20), 4865-4884.

**Elçi, E.** (2022). Politics of Nostalgia and Populism: Evidence from Turkey. *The British Journal of Political Science, 52*(2), 697-714.

**Elçi, E.**, Kirişçioğlu, E., & Üstübici, A. (2022). How COVID-19 Financially Hit Displaced Urban Refugees? Evidence from an Online Survey with Citizens and Syrian Refugees in Turkey. *Disasters, 45*(1), 240-263.

**Elçi, E.** (2022). Göçmenlere Karşı Tutumların Parti Tercihlerine Etkisi: Türkiye Örneği (The Impact of Anti-immigration Attitudes on Party Preference: The Case of Turkey), *İstanbul Ticaret Üniversitesi Sosyal Bilimler Dergisi-Türkiye’nin Göç Siyaseti Özel Sayısı, 21*, 46-73.

Çarkoğlu, A., **Elçi, E.**, Erol, F., & Paksoy, C. (2022) Popülizm Teorileri Işığında Türkiye’de Popülizmin Tarihsel Gelişimi: Siyasi Partiler Üzerine Bir İnceleme (A Historical Analysis of Populism in Turkey according to the Theories of Populism: An Analysis on Political Parties). *Anadolu Üniversitesi Sosyal Bilimler Dergisi, 22*(1), 323 - 348.

Çarkoğlu, A. & **Elçi, E.** (2021). Populist Attitudes Towards Syrian Refugees in Turkey. In E. Uslaner & N. Holtug (eds.), *National Values and Social Cohesion.* Colchester: ECPR Press.

Aytaç, S. E., Çarkoğlu, A., & **Elçi, E.** (2021). *Partisanship, elite messages, and support for populism in power. European Political Science Review, 13*(1), 23-39.

Üstübici, A., Kirişçioğlu, E., & **Elçi, E.** (2021). *Migration and Development: Measuring Migration Aspirations and the Impact of Refugee Assistance in Turkey,* ADMIGOV Deliverable 6.1, Amsterdam: University of Amsterdam.

**Elçi, E.** (2019). The rise of populism in Turkey: a content analysis. *Southeast European and Black Sea Studies, 19*(3), 387-408.

Aytaç, S. E., & **Elçi, E.** (2019). Populism in Turkey. In D. Stockemer (ed.). *Populism Around the World.* Cham: Springer.

Çarkoğlu, A., & **Elçi, E.** (2018). Alevis in Turkey. In P. S. Rowe (Ed). *Routledge Handbook of Minorities in the Middle East.* London & New York: Routledge.

### Research Projects

Political Party Representation of Anti-Immigration Attitudes: The Case of Turkey

2023 Elections and Migration Debate in Turkey

Nativism and Anti-Immigration in Turkey
